// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiGCuB8urP1t6g6gfNuBR80OKucYxaP_8',
    appId: '1:263436407957:web:e11b487cd4ef29c004379c',
    messagingSenderId: '263436407957',
    projectId: 'pragati-33f00',
    authDomain: 'pragati-33f00.firebaseapp.com',
    storageBucket: 'pragati-33f00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDybXsgj6fJSfDE8o7VeInnL2z451pq51U',
    appId: '1:263436407957:android:3fc72b391eb6adff04379c',
    messagingSenderId: '263436407957',
    projectId: 'pragati-33f00',
    storageBucket: 'pragati-33f00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxC8nSDW2JZ23x1toc4lcbsva9WYRLNfo',
    appId: '1:263436407957:ios:4e0c08534aa1547c04379c',
    messagingSenderId: '263436407957',
    projectId: 'pragati-33f00',
    storageBucket: 'pragati-33f00.appspot.com',
    iosBundleId: 'com.example.pragatiV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxC8nSDW2JZ23x1toc4lcbsva9WYRLNfo',
    appId: '1:263436407957:ios:c0f41893bfea09fe04379c',
    messagingSenderId: '263436407957',
    projectId: 'pragati-33f00',
    storageBucket: 'pragati-33f00.appspot.com',
    iosBundleId: 'com.example.pragatiV1.RunnerTests',
  );
}
